/**
 * Bercy
 * Bercy mobile application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Comment { 
    id?: number;
    issueId?: number;
    sender?: string;
    date?: string;
    text?: string;
}

