/**
 * Bercy
 * Bercy mobile application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Priority } from './priority';


export interface Issue { 
    id?: number;
    subject?: string;
    contract?: string;
    dateCreation?: string;
    dateLastUpdate?: string;
    category?: string;
    /**
     * Le statut du ticket
     */
    status?: Issue.StatusEnum;
    priority?: Priority;
}
export namespace Issue {
    export type StatusEnum = 'OPEN' | 'WAITING' | 'CLOSED';
    export const StatusEnum = {
        Open: 'OPEN' as StatusEnum,
        Waiting: 'WAITING' as StatusEnum,
        Closed: 'CLOSED' as StatusEnum
    };
}


